# Deploy to Render.com (Free Tier)
services:
  - type: web
    name: steam-recommender-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m src.main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: steam-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: false  # Manual deploys for free tier

databases:
  - name: steam-db
    plan: free  # PostgreSQL free tier 