# deployment/docker/docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: ../..
      dockerfile: deployment/docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/app.db
      - USE_REDIS=true
      - REDIS_URL=redis://redis:6379
    volumes:
      - ../../data:/app/data
      - ../../src:/app/src
    depends_on:
      - redis
    command: python -m src.main
  
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
  # Optional: Add PostgreSQL for production-like environment
  # postgres:
  #   image: postgres:13-alpine
  #   environment:
  #     POSTGRES_DB: steam_recommender
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  redis_data:
  # postgres_data: 